FuelLabs/docs-hub

src/components/CodeImport.tsx, src/components/ExampleBox.tsx, src/components/GraphqlCodeExample.tsx, src/components/Heading.tsx, src/components/Layout.tsx, src/components/Pre.tsx, src/components/SidebarLink.tsx, src/components/SidebarSubmenu.tsx, src/imports.ts, src/pages/sitemap.xml.ts, src/screens/DocPage.tsx, src/styles/index.css
=> fix: styles fixes and some improvements

scripts/sync-repos.sh
fixes /docs/sway and /docs/fuels-rs pages by renaming the ignored README.md files to index.md
=> fix: README files

package.json, pnpm-lock.yaml, src/components/Layout.tsx, src/components/List.tsx, src/components/MobileMenu.tsx, src/components/Paragraph.tsx, src/components/Pre.tsx, src/components/Sidebar.tsx, src/components/SidebarLink.tsx, src/components/SidebarSubmenu.tsx, src/components/Table.tsx, src/lib/md-doc.ts, src/pages/_app.tsx
Fixes several issues on mobile:
- table sizes
- code snippet font sizes
- home page mobile menu
=> fix: responsiveness

README.md
Ran into a bit of trouble trying to get changes from a WIP branch to be displayed in the dev setup, so I thought I'd add a blurb to help future users.
=> docs: add blurb for submodule updating to `README`

src/components/Layout.tsx, src/styles/index.css
On this PR;
- Fix the header on the top event when the user scrolls the page.
- Fix content size on mobile to make sure documentation is rendered inside the view without lateral scroll.
=> feat: improve scrollviews

src/components/Header.tsx, src/components/Heading.tsx, src/components/Layout.tsx, src/components/TableOfContent.tsx, src/screens/DocPage.tsx, src/styles/index.css
=> fix: scroll anchor

docs/guides/docs/quickstart/building-a-smart-contract.mdx, docs/guides/examples/quickstart/counter-contract/Cargo.lock, docs/guides/examples/quickstart/counter-contract/Cargo.toml, docs/guides/examples/quickstart/counter-contract/Forc.lock, docs/guides/examples/quickstart/counter-contract/tests/harness.rs
Bumping template in Sway repo broke playwrite test. Fixes #76
=> docs: Fixing quickstart tests

src/config/constants.ts, src/screens/HomePage.tsx
=> docs: adding sway playground

scripts/update-latest/gitUtils.mjs, scripts/update-latest/updateLatest.mjs
fixes an issue with updating the latest submodules
=> fix: latest branches

src/components/Sidebar.tsx
fixes the mobile nav on the guides page
=> fix: mobile nav in guides

docs/guides/docs/installation/index.mdx
Hot fix for [issue/123](https://github.com/FuelLabs/docs-hub/issues/123).
=> fix: hot-fix for {props.fuelTestnet} not working properly

docs/guides/docs/guides.json, docs/guides/docs/running-a-node/running-a-beta-4-node.mdx
- Javascript was not capitalized
- ip 127.0.0.1 would only work for local connections so when someone is trying connecting externally it would not work
=> fix: Small docs changes

docs/guides/docs/running-a-node/running-a-testnet-node.mdx
=> fix: --sync-header-batch-size flag

docs/guides/docs/intro-to-sway/prerequisites.mdx, docs/guides/docs/intro-to-sway/typescript-sdk.mdx, docs/guides/docs/quickstart/building-a-frontend.mdx, spell-check-custom-words.txt, tests/utils/fixtures/index.ts
fixes for the new release of the Fuel Wallet
=> chore: bump release-wallet

docs/beta-4/fuels-wallet/packages/docs/docs/dev/abis.mdx, docs/beta-4/fuels-wallet/packages/docs/docs/dev/accounts.mdx, docs/beta-4/fuels-wallet/packages/docs/docs/dev/assets.mdx, docs/beta-4/fuels-wallet/packages/docs/docs/dev/connecting.mdx, docs/beta-4/fuels-wallet/packages/docs/docs/dev/connectors.mdx, docs/beta-4/fuels-wallet/packages/docs/docs/dev/getting-started.mdx, docs/beta-4/fuels-wallet/packages/docs/docs/dev/networks.mdx, docs/beta-4/fuels-wallet/packages/docs/docs/dev/signing.mdx, docs/beta-4/fuels-wallet/packages/docs/src/hooks/useFuel.tsx, package.json, pnpm-lock.yaml, src/lib/imports.ts
=> fix: remove old wallet examples

.github/ISSUE_TEMPLATE/config.yml, .github/workflows/close-support-questions.yml
* Encourage people to go to the forum for general questions
* Introduce workflow to close general questions raised as issues w/a message to go to the forum
=> ci: introduce support flow for issues

src/components/Header.tsx, src/components/Pre.tsx, src/hooks/useShowWarning.tsx, src/lib/plugins/fix-indent.ts, src/lib/plugins/plugins.ts, src/pages/_app.tsx, src/screens/DocPage.tsx
- fixes syntax highlighting issues on fuels-ts commands and gql recipes pages
- fix to keep nightly docs warning closed during session
- fixes code indentations (ex: see the instantiating predicates page in fuels-ts docs)
closes https://github.com/FuelLabs/devrel-requests/issues/5
=> style: fixes

scripts/update-nightly/gitUtils.mjs, scripts/update-nightly/updateSubmodules.mjs
updates the nightly docs, and fixes the issue with it updating in the CI
=> fix: sway nightly docs

src/lib/plugins/plugins.ts
fixes images on https://docs.fuel.network/docs/nightly/fuels-ts/creating-a-fuel-dapp/
=> fix: fuels-ts nightly docs images

docs/guides/docs/intro-to-sway/typescript-sdk.mdx, docs/guides/docs/quickstart/building-a-frontend.mdx
=> docs: updated @fuels/connectors to v0.2.2

.github/actions/setup-node/action.yaml, .gitmodules, .vscode/settings.json, contentlayer.config.ts, scripts/clean-build-files.mjs, scripts/generate-links/getDocs.mjs, scripts/generate-links/getOrders.mjs, scripts/generate-links/index.mjs, scripts/update-nightly/updateSubmodules.mjs, src/components/SidebarSection.tsx, src/config/docs.json, src/config/paths.json, src/lib/md-doc.ts
Repo name change and removal of old migration info inside 'guides'
https://github.com/FuelLabs/migrations-and-disclosures
=> docs: Rename Migrations and Disclosures

src/config/versions.json
- Bumped the version of fuels-wallet with fixes for dependency packages with flagged vulnerabilities.
=> docs: Update Main docs

package.json, pnpm-lock.yaml, src/components/AskCookbook.tsx, src/lib/types.d.ts, src/pages/_app.tsx
The AI assistant and co-pilot is trained on all existing Fuel resources (source code, docs website, etc) and is available as a standalone modal, embeddable as a button on any page (recommended for technical docs). It answers developer questions about building projects on Fuel, acting as an enhanced and streamlined technical documentation search tool as well as a Solidity coding co-pilot.
Ask Cookbook AI could also access context from thousands of data sources indexed by Cookbook.dev in addition to Fuel-specific data sources, providing the best blockchain developer-focused answers of any chatbot on the market. Cookbook will assist in the tuning and calibration of the AI assistant to ensure the highest answer quality.
https://docsbot-demo-git-fuel-cookbookdev.vercel.app/docs/intro/what-is-fu …
=> feat: Cookbook Onboard (AI Assistant) Integration

src/components/VersionDropdown.tsx
We still want testnet in appropriate places like faucet so this is simply a UI change
=> feat: Update from Testnet to Stable in the dropdown menu

src/lib/plugins/mdbook-example-import.ts
Fixed the build error from #485
=> chore: fixing build error
